### ISSUE TITLE
Do you have plans to support TypeScript?

### ISSUE THREAD

**Issue by Sakaki-Ya** [cutterbl/SoundTouchJS#11]
Thank you for making a very nice plugin.

As the title suggests, do you have any plans to support TypeScript?
I'm very much looking forward to it.

**Comment by cutterbl** [comment]
I am a bad host. Just now seeing this. In answer to your question, I currently have no intention of refactoring it into TypeScript, but that shouldn't prevent anyone from using it. TS is just compiled down into ES in the end anyway, so it shouldn't be an issue. If you find one, let me know.
