### ISSUE TITLE
How to use PitchShifter as an AudioNode

### ISSUE THREAD

**Issue by qingwufong** [cutterbl/SoundTouchJS#12]
Hi cutterbl, 
    sorry about ask question here. How to use PitchShifter as an AudioNode? code like this:

```
      const audio = document.getElementsByTagName('audio')[0];
      const audioCtx = new (window.AudioContext || window.webkitAudioContext)();
      const gainNode = audioCtx.createGain();
      let shifter;

      const source = audioCtx.createMediaElementSource(audio);
      shifter = new PitchShifter(audioCtx, 1024);
      source.connect(gainNode);
      gainNode.connect(shifter.node);
      shifter.connect(audioCtx.destination)
```

thanks!

**Comment by cutterbl** [comment]
@qingwufong Thanks for reaching out. Unfortunately SoundTouchJS does not, yet, support this. Here's a [small write up](https://cutterscrossing.com/development/ecmascript/webaudioapi/soundtouchjs/audioworklets/2020/05/14/why-is-soundtouch-working-as-a-pseudo-node/) on the 'why'.
