### ISSUE TITLE
Feed PitchShifter new Buffers being downloaded from stream

### ISSUE THREAD

**Issue by 432player** [cutterbl/SoundTouchJS#13]
Is it possible to somehow update the PitchShifter with more buffers while it's playing?
We wish to use this PitchShifter on a radio station stream, what would be the best way to go about this?

Thanks for this library! very useful

**Comment by cutterbl** [comment]
Unfortunately, the way that SoundTouchJS currently works is to give it a full file upfront. This speaks to how it currently chunks bits into an intermediary array prior to processing. At some point I hope to refactor to process on the fly, which would allow for this sort of action, but at the moment it just doesn't work this way.

**Comment by RSchmitzHH** [comment]
Hi @cutterbl , is this plan still in place? In case not, does anyone know an alternative package for exactly this?
