### ISSUE TITLE
Crackling sound with newest Google Chrome version

### ISSUE THREAD

**Issue by zoschfrosch** [cutterbl/SoundTouchJS#16]
Hi,

great piece of software! I never thougt that online audio processing with javascript is possible, but your library does it with a very good performance. I use your library since several months, until a few days ago without any problems. But with the newest update of Google Chrome from version 89.0.4389.82 to 89.0.4389.90, the sound became distorted and crackling. Same thing with Edge, Firefox works well with no distortions. The problems occur with Windows 10. With Ubuntu 20.04 I cannot reproduce them because Chrome is still on the older version.
Playing the same audio files with the html audio element works fine. I experimented with a greater buffer size, up to 16384. This reduced the distortion, but then the tracks (I have several instrument tracks of the same piece of music) run out of sync.
Do you have any idea what's going on? Are there other users with the same problem?

Kind regards
Thomas

**Comment by Ema38** [comment]
I'm having the same problem.
I’m using Windows 10, Chrome.  
This did not happen before.  
It's like it plays intermittently.  
Also, the speed seems to decrease slightly.

**Comment by zoschfrosch** [comment]
I asked some friends to try it on their notebooks/PC's. Everybody with Windows (10 and 7) and the Chrome version 89.0.4389.90 has this problem. On Linux and MacOSX, also with this Chrome-Version, everthing is ok. Checked the change log of Chrome, they mention a security fix of the audio functionality. Unfortunately, I cannot open the detailed description, seems to be confidential.

**Comment by Eliastik** [comment]
Related to this Chromium issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1187016#c65
This is related to a security bug fixed in Chrome/Chromium 89 affecting the scriptProcessorNode API. The Chrome Security team suggest to use the AudioWorklet API instead (try the AudioWorklet implementation of SoundTouchJS: https://github.com/cutterbl/soundtouchjs-audio-worklet).
