### ISSUE TITLE
Is it possible to export the edited file?

### ISSUE THREAD

**Issue by cvial** [cutterbl/SoundTouchJS#2]
Hello,

Thanks for the great work !
I was wondering if it was possible to export the edited file after all the changes?

Let me know,
Thanks

**Comment by cutterbl** [comment]
@cvial Thanks for reaching out! Yes, it is certainly possible to capture the audio and funnel it to an export. I personally haven't done it, but I looked at the [OnlineToneGenerator](http://onlinetonegenerator.com/pitch-shifter.html) for inspiration, when I was retooling SoundTouchJS. That specific example does recording. Look at they're [recorder file](http://onlinetonegenerator.com/js/vendor/recorder.js), as well as bits of the [page's core file](http://onlinetonegenerator.com/js/vendor/soundtouch/st.min.js) starting with line 1189. Remember, my version of SoundTouch is different from theirs, so you may require some adjustments, but hopefully they're example will help push you in the right direction.
