### ISSUE TITLE
the page is broken when pitch is minus

### ISSUE THREAD

**Issue by MissLiu34** [cutterbl/SoundTouchJS#21]

**Comment by cutterbl** [comment]
That makes sense. Fairly certain pitch has to be 0 or higher, with default to 1.

**Comment by MissLiu34** [comment]
When I want to change voice to a male voice, it's common to change the pitch to a negative number. But now how to do it?How to make one's voice deeper?

**Comment by MissLiu34** [comment]
To change the voice to a male voice, the usual practice is to use a negative number. But now should I use a decimal?
And what is the range of pitch?
