### ISSUE TITLE
The bufferSize passed to the PitchShifter has no effect

### ISSUE THREAD

**Issue by jraoult** [cutterbl/SoundTouchJS#4]
While tweaking the buffer size of the `PitchShifter` I realised it had no effect. This is because the value is not passed down to the `getWebAudioNode`:
https://github.com/cutterbl/SoundTouchJS/blob/bad98fb07c2fd55fb82a5a3fa4ffd162ff490648/src/PitchShifter.js#L48-L56
Happy to provide a patch it you want it @cutterbl .

**Comment by cutterbl** [comment]
Always open for PR.

**Comment by jraoult** [comment]
> Always open for PR.

Here we go @cutterbl https://github.com/cutterbl/SoundTouchJS/pull/5

**Comment by cutterbl** [comment]
Merged. v0.1.8 published to npm. Thanks for the assist.
