### ISSUE TITLE
Error "Unexpected token `export`" when importing soundtouchjs

### ISSUE THREAD

**Issue by sharad-s** [cutterbl/SoundTouchJS#6]
Unable to use soundtouchjs as intended because the dist file uses the `export` keyword which errors out on load. 

The line can be viewed here: 
https://github.com/cutterbl/SoundTouchJS/blob/53d5b726755dbe85cd2ffe34efb974b4757006fa/dist/soundtouch.js#L1147

The error looks like this: 
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/8727763/77812241-04f37900-706e-11ea-8ef1-77c75c3459d0.png">

I fixed this issue locally by changing the `export` keyword to `module.exports =` as so: 
<img width="842" alt="image" src="https://user-images.githubusercontent.com/8727763/77812261-281e2880-706e-11ea-8da8-ed064ac9ea70.png">

However, it would be great to have this fixed.

Thanks!

**Comment by cutterbl** [comment]
That's because I don't currently provide a commonJS build of SoundTouchJS. You can fork the project and create your own commonJS build, or submit a Pull Request if you like, until I do create one.
